### ISSUE TITLE
Communicate with Xaml window 

### ISSUE THREAD

**Issue by ksobon** [jhubers/pCOLAD-for-Dynamo#2]
i have been following your discussions with Dynamo team trying to figure out how to launch a xaml window control from Custom Ui node in Dynamo. There was a point when you guys talked about adding an event to the Utilities method that was called from AST Func call to communicate with the window. Would you be able to show me the relevant example of how that can be done? 

I am trying to build a node with a single input. Input is a string that contains html code. When button is pressed on a custom ui node it launches the window that has a web browser control embedded. I want the input string to be rendered into the browser control but i cant figure out how to send it to the control. Would you be able to help?

**Comment by jhubers** [comment]
I might be able to help when back from holiday august 28...
Hans

Verzonden met mijn Windows Phone
________________________________
Van: Konrad K Sobon<mailto:notifications@github.com>
Verzonden: ‎7-‎8-‎2016 16:02
Aan: jhubers/pCOLAD-for-Dynamo<mailto:pCOLAD-for-Dynamo@noreply.github.com>
Onderwerp: [jhubers/pCOLAD-for-Dynamo] Communicate with Xaml window (#2)


i have been following your discussions with Dynamo team trying to figure out how to launch a xaml window control from Custom Ui node in Dynamo. There was a point when you guys talked about adding an event to the Utilities method that was called from AST Func call to communicate with the window. Would you be able to show me the relevant example of how that can be done?

I am trying to build a node with a single input. Input is a string that contains html code. When button is pressed on a custom ui node it launches the window that has a web browser control embedded. I want the input string to be rendered into the browser control but i cant figure out how to send it to the control. Would you be able to help?

**Comment by jhubers** [comment]
Hi,

Are you still interested in this issue, or did you already find the answer?

**Comment by ksobon** [comment]
I did figure it out. Thank you for offering to help.

Konrad

**Comment by huythach** [comment]
@ksobon @jhubers I want to do something as same as what @ksobon wanted to do: Getting input values from a Dynamo node, then display these values as a graph in a separated window.
Could you share your solution? Thanks.

**Comment by ksobon** [comment]
That project was published here: https://github.com/BadMonkeysTeam/Mandrill

**Comment by huythach** [comment]
Could you tell in which file you do that?
